### ISSUE TITLE
Nice paper!

### ISSUE THREAD

**Issue by sneakers-the-rat** [losonczylab/behaviorMate#2]
Just saw the [preprint](https://doi.org/10.1101/2023.12.04.569989) - nice stuff, completely agree that many networked machines is the way to do neuroscientific experiments (vs. One big fast machine or a bunch of independent machines with TTL pulses running between them).

See autopilot for prior art on networked behavior frameworks ❤️
- paper: https://doi.org/10.1101/807693
- repo: https://github.com/auto-pi-lot/autopilot
- docs: https://docs.auto-pi-lot.com
- wiki: https://wiki.auto-pi-lot.com/

**Comment by sneakers-the-rat** [comment]
Ok! Just saying hi, like the work, sorry for the noise on the issue tracker ♥

**Comment by jbowler06** [comment]
no worries - I should have replied, but so much time had passed; thanks for the comments. There's a new revision on the paper up on bioRxiv: https://www.biorxiv.org/content/10.1101/2023.12.04.569989v5 and hopefully the update will be online at eLife shortly: https://elifesciences.org/reviewed-preprints/97433v1#tab-content

Hoping to move issues tracking to github so I figured it made sense to clean up the thread.

**Comment by sneakers-the-rat** [comment]
totally yes, like i said sorry for the noise, glad to see another group carrying on the worked of networked behavior systems since i've taken a break to do something else. will take a look at the revision!
